### ISSUE TITLE
Usage information

### ISSUE THREAD

**Issue by Storyyeller** [ridiculousfish/HexFiend#113]
It would be nice if there was some documentation about how to actually use Hex Fiend. I spent the last 20 minutes unsuccessfully trying to figure out how to diff two files. I looked through all the menus, searched through the issues on Github, and even tried skimming the source code, but still couldn't figure it out. If a feature isn't visible, it may as well not exist.

Update: I eventually figured it out. You have to first open two different files, and then in the file menu there will be a new option to compare the files. I wish it weren't so hard to discover though.

**Comment by xobzoo** [comment]
Thank you for that update, @Storyyeller!  I spent fewer than 20 minutes, but only because resorted to searching online and found your message (instead of discovering it within Hex Fiend itself).

(In this particular case, I used the Help menu to search for "`diff`" — which it could not find.  I suppose "Compare" is a fair term for it, but wasn't very discoverable because my eyes skimmed over the grayed-out menu entries when I went searching before.  I considered that I might need both files open at the same time, but somehow missed the File menu after opening the second file; that one's my fault.)

I found Hex Fiend via homebrew.  Running `brew cask homepage hex-fiend` sends me to the ["stale"](https://github.com/ridiculousfish/HexFiend/issues/114) [website](http://ridiculousfish.com/hexfiend/) which looks really helpful.  In fact, it's that page which caused me to know/believe that diffing files was possible.  However, nothing on there indicated _how_ to use the tool.  Next stop was to check the github page, which has essentially no documentation, but did eventually lead me to the answer.

I don't mean to sound like an ungrateful user, but a brief tutorial/walk-through/documentation page would be _very_ helpful for anyone just starting out.  Even just a "Common Actions" section near the bottom of the [README](https://github.com/ridiculousfish/HexFiend#more-information) would be great.

**Comment by kainjow** [comment]
I added the list of features on the website to the readme and updated the diff part with a sentence on how to use.

**Comment by xobzoo** [comment]
Excellent!  Thanks, it looks great.
