### ISSUE TITLE
Japanese (Shift-JIS) not displaying as expected

### ISSUE THREAD

**Issue by gingerbeardman** [ridiculousfish/HexFiend#120]
Seems to be displaying it as single byte characters rather than double byte?

File: [Script000.dat.zip](https://github.com/ridiculousfish/HexFiend/files/1663819/Script000.dat.zip)

Encoding set to: Other > Japanese (Shift JIS)

Hex Fiend
![screen shot 2018-01-25 at 11 50 05](https://user-images.githubusercontent.com/49612/35387022-1561fb9a-01c6-11e8-8bf2-8153a9172de2.png)

Compared that to the following:

Synalyze-It! (encoding: Shift_JIS)
![screen shot 2018-01-25 at 11 49 50](https://user-images.githubusercontent.com/49612/35387021-1547ecb4-01c6-11e8-8af2-c41633b2ef29.png)

010 Editor (encoding: Japanese)
![screen shot 2018-01-25 at 11 52 58](https://user-images.githubusercontent.com/49612/35388075-3f87b08c-01ca-11e8-8bcb-0b7e2817d91e.png)

0xED (encoding: Japanese Shift JIS)
less good, but at least it displays selection OK in status bar
![screen shot 2018-01-25 at 12 21 53](https://user-images.githubusercontent.com/49612/35388132-77cf03fa-01ca-11e8-96a4-cfb39f5ed982.png)

**Comment by kainjow** [comment]
It appears Shift JIS is variable length encoding, but HF currently just supports a fixed width for encodings, and Shift JIS is treated as 1 byte per character as seen here: https://github.com/ridiculousfish/HexFiend/blob/aca0c6c4b120e5a7822500d58594e27093a274b4/framework/sources/HFFunctions.m#L676

It might be a large amount of work to address this. The problem is what do you show if 1 byte is at the end of the row and the 2nd byte is at the next row? Same problem with UTF-8, and technically UTF-16 which can span 4 bytes AFAIK. A potential generic way to fix would be to read up to max bytes for any encoding (6, for utf-8?) and then with each byte generate a string with the encoding while the string's character length is 1.

Maybe simpler to just always do a fixed width display, knowing it won't be perfect, but allow the data inspector to choose an encoding for the selected text.

**Comment by gingerbeardman** [comment]
In another app I use, any wrapping value is displayed poking out on the end of the first line, and a blank space is shown at the beginning of the next line.

Dat inspector is not ideal because my use case is that I need to visually scan a file with text rendered in place.

**Comment by kainjow** [comment]
Thanks for the details. Since this is how it's intended to work currently, I'm moving discussion to a separate thread (#185) to combine references from previous reports.
