### ISSUE TITLE
moveto (absolute file positioning)

### ISSUE THREAD

**Issue by jaroslov** [ridiculousfish/HexFiend#147]
I've got a few file formats where the absolute offset of fields are marked in headers. Being able to just "moveto" would be nice.

**Comment by ahti** [comment]
There are a few undocumented commands. You can see all commands and how they're implemented in [`HFTclTemplateController.m`](https://github.com/ridiculousfish/HexFiend/blob/master/app/sources/HFTclTemplateController.m).

`goto` will do what you want, although not relative to the start of the file, but to the anchor point of the template (which is the start of the file by default, so that should be fine).

**Comment by kainjow** [comment]
@ahti if you've found a bug let me know. It should be using anchor: https://github.com/ridiculousfish/HexFiend/blob/43bf4aa57f399ee20d71cef9a68a7cc80a086985/app/sources/HFTemplateController.m#L352

I'll document these missing functions.

**Comment by kainjow** [comment]
Added documentation for `goto` in fc1bbe84ab8ec61087af00f4eb87f060f438413d.
