### ISSUE TITLE
get_sparkle.sh fails behind proxy

### ISSUE THREAD

**Issue by ncoelle** [ridiculousfish/HexFiend#152]
If you build HexFiend on a system behind a proxy server, the download of Sparkle fails even if you exported http_proxy and https_proxy in your environment.

**Solution**: In the Build Settings of the project add the User-Defined settings 'http_poxy' and 'https_proxy' and enter your proxy server as value e.g. `http://myproxy:port/`. If you have to use a proxy user, it should be `http://user:password@myproxy:port/`

**Comment by kainjow** [comment]
Interesting. Can you try out this command and let me know if it works for you? If so we could switch to that instead:

`nscurl https://github.com/sparkle-project/Sparkle/releases/download/1.19.0/Sparkle-1.19.0.tar.bz2`

If it works it should output a bunch of junk in Terminal. Otherwise you should see an error.

**Comment by kainjow** [comment]
Great! Could you make a pull request?
