### ISSUE TITLE
No data window displayed anymore

### ISSUE THREAD

**Issue by JP-NYC** [ridiculousfish/HexFiend#195]
HexFiend 2.11 been working on High Sierra until recently. Now program launches and shows in the Dock but it does not open a window with hex data. Most of the menu items are greyed out because no window is open. 
'Open File' doesnt help.
I have tried deleting the prefs file

**Comment by JP-NYC** [comment]
Problem solved. Bad system font used by app!

**Comment by kainjow** [comment]
Can you share what the font was? I can look into fixing the issue.

**Comment by JP-NYC** [comment]
it was one of the system fonts - Monaco

you can simulate the problem by removing the font from your system\library


________________________________

**Comment by kainjow** [comment]
Seeing as Monaco is in /System/LIbrary/Fonts which normally is unmodifiable due to System Integrity Protection and on macOS Catalina will be on a read-only volume, this shouldn't be a normal situation, and until Apple removes the font we can assume it is installed and available, unless there is some other valid environment in which it is not.
