### ISSUE TITLE
Can't save executable-type files

### ISSUE THREAD

**Issue by tpwrules** [ridiculousfish/HexFiend#214]
I'm hacking up a windows .exe with Hex Fiend v2.12b2, and I can edit it to my heart's content, but I can't save it.

When I try, I get a dialog from the OS asking me to give Hex Fiend permission to install a new helper tool. If I put in my password and hit "Install Helper", I get the message "Failed to launch and connect helper.", "The operation couldn’t be completed. (CFErrorDomainLaunchd error 4.)". If I hit "Cancel" instead, I get the message "Failed to launch and connect helper.", "The operation was cancelled.". In either case, Hex Fiend then tells me that the document couldn't be saved.

This same exact problem happens in v2.11. In v2.4, I still have to give permission to install a helper tool every single time I save an executable file (and then permission again afterwards to "make changes"), but it does at least save correctly.

This problem also happens when trying to edit e.g. MacOS executables. It does not happen when trying to save an "innocuous" file type, like .jpg. I assume it's the OS trying to save me from myself, but surely there is some way to disable it or permanently give authorization?

**Comment by kainjow** [comment]
What are file permissions? Maybe somehow it has executable and that is causing things to trip up? What macOS version are you on?

**Comment by tpwrules** [comment]
I'm still on macOS 10.14.6 . But I found out that the "executable-type" thing is a red herring.

It seems the "helper tool" dialog triggers on saving to a write-protected file, regardless of the file's contents or +x bit status. There's still something weird going on because v2.4 could write to such a file (after filling in your password twice) but v2.12b2 can't. Maybe there could be a check for write access before attempting the save operation? I'm not sure what the correct behavior should even be but the current behavior is a bit misleading.

Anyway, a quick repro is:
`echo "hello" > ~/hello.txt; chmod 444 ~/hello.txt; open -a "Hex Fiend" ~/hello.txt`

Then try and save the file without making any changes. It should give you the install helper dialog.

**Comment by kainjow** [comment]
I think this behavior exists because HF allows writing to drives, which aren't user writable, so it assumes if it can't write, it needs to elevate ownership and does this through some funky code (see `HF_NO_PRIVILEGED_FILE_OPERATIONS`). I've long wondered whether this should continue to exist in HF or not. The App Store version doesn't ship this part of the code anyways since it's not allowed (it uses `SMJobBless`, although in 10.14 Apple added `requestAuthorizationOfType:completionHandler:` but it's extremely limited and doesn't support the low-level file operations that HF requires).

**Comment by kainjow** [comment]
This is expected behavior. The file doesn't have write access. You'd get the same error with any other program that tries to open the file for writing, for example `nano`. Even TextEdit will give you the "this file is unlocked" and then if you unlock it (it will give it write permission).

I'm going to close.

**Comment by krackers** [comment]
@kainjow I'm not sure if it's related, but on 10.9 at least I can replicate this issue where SMJobBless fails from Hex Fiend 2.9 onwards (it works fine in 2.8):

```
10/21/20 4:18:50.452 PM launchdadd[23465]: FAILURE: Code <SecStaticCode 0x7fc198f0d7e0 [0x7fff7b209f00]> failed requirement (identifier "com.ridiculousfish.HexFiend.PrivilegedHelper" and certificate leaf[subject.CN] = "Developer ID Application: Kevin Wojniak") with error "The operation couldn’t be completed. (OSStatus error -67050.)"
```

```
10/21/20 4:18:50.452 PM launchdadd[23465]: FAILURE: Job com.ridiculousfish.HexFiend.PrivilegedHelper could not be installed from /Applications/Hex Fiend.app/Contents/Library/LaunchServices/com.ridiculousfish.HexFiend.PrivilegedHelper, reason 3.
```

I tried digging a bit, but the `SMPrivilegedExecutables` key-value in the `info.plist` of the main app and embedded in the executable of the helper tool seemed the same between the two, so I'm not sure what changed.
