### ISSUE TITLE
hexf: Prints usage on pipe

### ISSUE THREAD

**Issue by eaigner** [ridiculousfish/HexFiend#246]
The `hexf` commandline tool seems a bit flaky. For instance, copy this base64 string to clipboard 

    YQBi

The data is ASCII `a{NULL}b`. Now pipe it to `hexf` using `base64` decode like so

    pbpaste | base64 --decode | hexf

Now on the first invocation this works, and HexFiend opens correctly. On subsequent invocations `hexf` just prints its usage string.

**Comment by kumowoon1025** [comment]
The pasteboard doesn't exactly behave as you might expect from a simple fifo buffer I think is what you are seeing. The same doesn't happen if you use `print` or `echo` does it?

**Comment by kainjow** [comment]
Thanks! I added some code a while back in an attempt to fix a hang when running `hexf` without any args. Turns out that broke piping. The idea was no arguments and no stdin would be an error and would then show the usage. But I don't think that can be done (?). For example if you run `wc` without args, it also hangs waiting on stdin. I'm removed that code and it'll just have to be lived with as standard behavior I suppose (unless someone knows otherwise).
