### ISSUE TITLE
Giant Overlapping text in v2.13.0b4

### ISSUE THREAD

**Issue by NPAssoc** [ridiculousfish/HexFiend#267]
When I tried out v2.13.0b4, the type in the hex & character display was gigantic and overlapping, so it was completely unreadable. So I dropped back to v2.12. Changing fonts didn't help. Reducing the font size using "smaller" reduce the size of the text, but it was still overlapping.

**Comment by kumowoon1025** [comment]
Woah, yeah that release was pretty much for testing the changes in the glyph rendering code, @kainjow did it look okay on your machine? I can't seem to find any workaround or anything, this is what it looks like (I tried opening in low resolution but it looks the same even if I don't)
<img width="924" alt="v2_13_0_b4" src="https://user-images.githubusercontent.com/5461515/84590376-f6fafc00-ae03-11ea-8f63-554fcf32e8d6.png">

**Comment by kainjow** [comment]
What macOS version are you using?

**Comment by kumowoon1025** [comment]
Okay, I wasn't able to build on my laptop because it's still on Mojave and the last Xcode supported on it can't open the project file. I did try the app on an older server running High Sierra, and got the same behavior, so maybe the difference is the changes that came with Catalina.

So far, I could replicate on Mojave, High Sierra. Catalina doesn't have the problem, I forgot to try running from the dmg first, but it works fine.

**Comment by NPAssoc** [comment]
Mojave.

**Comment by kumowoon1025** [comment]
Thanks to the old code being left in there, it's simple to switch back with `#if 1`, it resolves the regression on pre-Catalina systems (or just use b3, pretty much same thing), but what exactly is the cause I wonder. Is system fonts new in Catalina?

**Comment by kainjow** [comment]
I just posted b5 with the change reverted.

That explains why it was so easy to make the change this time, when I had tried earlier and couldn't get it working. I must have done that on 10.14 :). Apple must have changed something in CoreText on 10.15. Anyways, back to the drawing board.
