### ISSUE TITLE
Line numbers are not expanding

### ISSUE THREAD

**Issue by flyingclimber** [ridiculousfish/HexFiend#270]
There seems to be a weird wrapping issue with line numbers in 2.13 that wasn't present before. Any line number longer than 3 digits is wrapping to the next line in both hex and decimal.

<img width="897" alt="Screen Shot 2020-06-28 at 12 24 45" src="https://user-images.githubusercontent.com/640437/85956420-abd00580-b93a-11ea-8bba-22b1f14d6ebf.png">

**Comment by Siguza** [comment]
Came here because of this issue as well.

It appears the issue is only reproducible with the "Monaco" font selected though. With hexadecimal line numbers, the last digit always breaks onto a new line, no matter what. The issue exists with decimal line numbers as well, but since those are not prefixed with zeroes, it only happens at the bottom of the file, where the line numbers become long enough to span the entire column.

**Comment by kainjow** [comment]
Thanks for reporting. I'm looking into it.

**Comment by kainjow** [comment]
Looks like c4104ce32f93f1fa208485252c9491c0388b34d1 is the culprit.

**Comment by kainjow** [comment]
Should be fixed now. Can you please test out this version? I'll make it official if it looks good.

https://github.com/ridiculousfish/HexFiend/releases/tag/v2.13.1b1

**Comment by Siguza** [comment]
Yes, that build fixes it.  
Thanks for the insanely fast handling. :)

**Comment by kumowoon1025** [comment]
I think the difference is the use of CTFontExtractGlyphsForCharacters.

By the way, this is going off a bit of a tangent, but are there any plans to remove the support code for old targets?

I am guessing it's there for framework users and maybe so people can build for older systems if they need, but maybe a stable, rock solid *final* tagged release could be worked on that includes the code, still maintain it to a certain extent (fixes for critical bugs, security issues if they appear) but clean out the unused target and architecture conditionals/compatibility types in the master, release config builds with minimum OSX 10.10 I believe? Like there is a lot of boilerplate to juggle the HFFloat/CGFloat/float/double/long double/NSUInteger/unsigned long/unsigned long long and far too many more types and their conversions and operations.

At the very least I'm pretty sure the PPC code could go (though I don't know how much of it is actually functional, does anyone have something with a G4 to test?) maybe even i386 (I think all Intel Macs that could run Snow Leopard officially runs x86_64 binaries), and I know I've kept whining about this without doing much, but I think an under-the-hood UI revamp would be hugely welcomed by many, it'd make new features easier to implement.

But then again, apparently Macs are also going arm in a couple years now, so 🤷
Really curious how Rosetta 2 will fare in terms of performance, but I'm pretty sure Universal 2 binaries won't include `i386`


*Don't quote me on any info below, I sort of stopped trying to get 73d5122 working because I thought it might be worth it trying to subclass standard AppKit components and not lose performance*
Apparently text scaling changed on .15 for Catalyst related reasons if I understood correctly (they changed scaling to make the same point size font look similar on iPad and Mac) But the related property is in UI/NSTextView and attributed strings, which apparently results in them looking not even close on Mojave Macs and Catalina Macs if you're doing custom glyph rendering.

**Comment by flyingclimber** [comment]
So much better. Thank you!
