### ISSUE TITLE
Crash when copying content to clipboard from file

### ISSUE THREAD

**Issue by gingerbeardman** [ridiculousfish/HexFiend#96]
### How to
1. Select 0x0000-0xFFFF in a file larger than 64KB
2. Edit > Copy

### Expected
Should copy data to clipboard

### Actual
Crashes, hard

### Short log
```
Thread 16 Crashed:
0   com.ridiculousfish.HexFiend-Framework	0x00000001006b08e1 -[HFHexPasteboardOwner writeDataInBackgroundToPasteboard:ofLength:forType:trackingProgress:] + 529
1   com.ridiculousfish.HexFiend-Framework	0x00000001006bfa51 -[HFPasteboardOwner backgroundMoveDataToPasteboard:] + 81
2   com.apple.Foundation          	0x00007fff877eab3d __NSThread__start__ + 1243
3   libsystem_pthread.dylib       	0x00007fff9bb9e93b _pthread_body + 180
4   libsystem_pthread.dylib       	0x00007fff9bb9e887 _pthread_start + 286
5   libsystem_pthread.dylib       	0x00007fff9bb9e08d thread_start + 13
```

### Full log
https://pastebin.com/raw/r6cC0yRB

**Comment by kainjow** [comment]
Yep, buffer overflow. Looks like it was introduced with 3e19ebd.

**Comment by kainjow** [comment]
I had to actually paste to get it to crash. If you're using a clipboard history program then it will auto-paste and produce the crash immediately. Otherwise the manual paste elsewhere is required to crash. The crash occurs when HF produces data for the paste, which doesn't happen until something else attempts to read data from the clipboard.
